export const FETCH_SEARCH_START = "FETCH_SEARCH_START";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILLED = "FETCH_SEARCH_FAILLED";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_END = "FETCH_DATA_END";
